name: "Mood Analyze"
description: "Respond to new PR's with a gif representing the sentiment"
branding: 
  icon: 'at-sign'
  color: 'yellow'
inputs:
  GITHUB_TOKEN:
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
