on:
  pull_request:
    types: [opened, reopened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Analyze mood of PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mood Analysis Step
        uses: ./ #uses local latest version for testing purposes
        id: happy
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
