on:
  pull_request:
    types: [opened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Analyze mood of PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mood Analysis Step
        uses: TerabyteTiger/action-happyPR@v2
        id: happy
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
